name: Build Builder Image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docker/builder/**'
      - '.github/workflows/build-builder-image.yml'
  workflow_dispatch: # Allows  manually from the Actions tab

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-builder

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/builder/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          # Set cache layers to make future builds faster
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # JOB 2: Verify we can use this container
  test-container:
    needs: build-and-push
    runs-on: ubuntu-latest

    # Instead of use the standard Ubuntu tools, pull the image and run steps INSIDE it.
    container:
      image: ghcr.io/${{ github.repository }}-builder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check Java Version
        run: java -version

      - name: Verify Environment
        run: |
          echo "I am running inside the container built in the previous job!"
          cat /etc/os-release